# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml /app/
COPY src /app/src
COPY README.md /app/README.md

# Install dependencies and package
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir .

# Set entrypoint
ENTRYPOINT ["freecad-mcp"]
